/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomePage` | `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomePage/utils` | `/HomePage/utils`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PostsPage` | `/PostsPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ViewProfileScreen` | `/ViewProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage/Utils`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpPage/Utils`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpPage`; params?: Router.UnknownInputParams; } | { pathname: `/UI/Button/Button`; params?: Router.UnknownInputParams; } | { pathname: `/UI/TextBox/TextBox`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomePage` | `/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomePage/utils` | `/HomePage/utils`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/PostsPage` | `/PostsPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ViewProfileScreen` | `/ViewProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginPage/Utils`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpPage/Utils`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpPage`; params?: Router.UnknownOutputParams; } | { pathname: `/UI/Button/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/UI/TextBox/TextBox`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomePage${`?${string}` | `#${string}` | ''}` | `/HomePage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomePage/utils${`?${string}` | `#${string}` | ''}` | `/HomePage/utils${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/PostsPage${`?${string}` | `#${string}` | ''}` | `/PostsPage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ViewProfileScreen${`?${string}` | `#${string}` | ''}` | `/ViewProfileScreen${`?${string}` | `#${string}` | ''}` | `/LoginPage/Utils${`?${string}` | `#${string}` | ''}` | `/LoginPage${`?${string}` | `#${string}` | ''}` | `/SignUpPage/Utils${`?${string}` | `#${string}` | ''}` | `/SignUpPage${`?${string}` | `#${string}` | ''}` | `/UI/Button/Button${`?${string}` | `#${string}` | ''}` | `/UI/TextBox/TextBox${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomePage` | `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomePage/utils` | `/HomePage/utils`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PostsPage` | `/PostsPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ViewProfileScreen` | `/ViewProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage/Utils`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpPage/Utils`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpPage`; params?: Router.UnknownInputParams; } | { pathname: `/UI/Button/Button`; params?: Router.UnknownInputParams; } | { pathname: `/UI/TextBox/TextBox`; params?: Router.UnknownInputParams; };
    }
  }
}
